linters:
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - deadcode
    - decorder
    - depguard
    - dogsled
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - execinquery
    - exhaustive
    - exportloopref
    - forbidigo
    - gocheckcompilerdirectives
    - gochecknoinits
    - ginkgolinter
    - goconst
    - gocritic
    - godot
    - goerr113
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomodguard
    - gomoddirectives
    - goprintffuncname
    - gosimple
    - govet
    - grouper
    - importas
    - ineffassign
    - loggercheck
    - maintidx
    - makezero
    - misspell
    - nakedret
    - nilerr
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tagliatelle
    - tenv
    - testableexamples
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - varcheck
    - wastedassign
    - whitespace
    
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - wrapcheck